#!/usr/bin/env npx tsx
/**
 * 프리뷰 보고서 생성 스크립트
 *
 * 사용법:
 *   npx tsx scripts/generate-preview.mts           # 최근 초안의 프리뷰 생성
 *   npx tsx scripts/generate-preview.mts --today   # 오늘 생성된 초안만
 */

import { config } from 'dotenv';
config();

import { readdir, readFile, mkdir, writeFile, stat } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

interface DraftInfo {
  filename: string;
  filepath: string;
  title: string;
  type: string;
  tags: string[];
  draft: boolean;
  date: string;
  description: string;
  coverImage?: string;
  hasInlineImages: boolean;
  inlineImageCount: number;
  wordCount: number;
  createdAt: Date;
}

async function getDrafts(todayOnly: boolean): Promise<DraftInfo[]> {
  const draftsDir = join(projectRoot, 'drafts');

  try {
    await stat(draftsDir);
  } catch {
    return [];
  }

  const files = await readdir(draftsDir);
  const mdFiles = files.filter(f => f.endsWith('.md'));

  const drafts: DraftInfo[] = [];
  const today = new Date().toISOString().split('T')[0];

  for (const filename of mdFiles) {
    const filepath = join(draftsDir, filename);
    const content = await readFile(filepath, 'utf-8');
    const fileStat = await stat(filepath);
    const { data, content: body } = matter(content);

    // 인라인 이미지 카운트
    const imageMatches = body.match(/!\[.*?\]\(.*?\)/g) || [];
    const hasInlineImages = imageMatches.length > 0;

    const draftInfo: DraftInfo = {
      filename,
      filepath,
      title: data.title || filename,
      type: data.categories?.[0] || 'unknown',
      tags: data.tags || [],
      draft: data.draft !== false,
      date: data.date || '',
      description: data.description || '',
      coverImage: data.image,
      hasInlineImages,
      inlineImageCount: imageMatches.length,
      wordCount: body.length,
      createdAt: fileStat.mtime
    };

    if (todayOnly) {
      const fileDate = fileStat.mtime.toISOString().split('T')[0];
      if (fileDate === today) {
        drafts.push(draftInfo);
      }
    } else {
      drafts.push(draftInfo);
    }
  }

  // 최신순 정렬
  drafts.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());

  return drafts;
}

async function generatePreviewReport(drafts: DraftInfo[]): Promise<string> {
  const today = new Date().toISOString().split('T')[0];
  const time = new Date().toLocaleString('ko-KR');

  let report = `# 포스트 프리뷰 보고서

**생성 날짜**: ${today}
**생성 시간**: ${time}
**초안 수**: ${drafts.length}개

---

`;

  if (drafts.length === 0) {
    report += '> 프리뷰할 초안이 없습니다.\n';
    return report;
  }

  for (const draft of drafts) {
    const emoji = draft.type === 'travel' ? '🧳' : '🎨';
    const statusEmoji = draft.draft ? '📝' : '✅';

    report += `## ${emoji} ${draft.title}

| 항목 | 값 |
|------|------|
| **파일명** | \`${draft.filename}\` |
| **유형** | ${draft.type} |
| **상태** | ${statusEmoji} ${draft.draft ? '초안' : '발행 준비'} |
| **작성일** | ${draft.date || '미지정'} |
| **글자 수** | ${draft.wordCount.toLocaleString()}자 |
| **커버 이미지** | ${draft.coverImage ? '✅ 있음' : '❌ 없음'} |
| **인라인 이미지** | ${draft.hasInlineImages ? `✅ ${draft.inlineImageCount}개` : '❌ 없음'} |

### 설명
${draft.description || '(설명 없음)'}

### 태그
${draft.tags.length > 0 ? draft.tags.map(t => `\`${t}\``).join(' ') : '(태그 없음)'}

### 예상 URL
\`/posts/${draft.date ? String(draft.date).slice(0, 7).replace('-', '/') : 'YYYY/MM'}/${draft.filename.replace('.md', '')}/\`

---

`;
  }

  // 요약
  const travelCount = drafts.filter(d => d.type === 'travel').length;
  const cultureCount = drafts.filter(d => d.type === 'culture').length;
  const totalImages = drafts.reduce((sum, d) => sum + d.inlineImageCount + (d.coverImage ? 1 : 0), 0);

  report += `## 📊 요약

| 항목 | 수량 |
|------|------|
| Travel 포스트 | ${travelCount}개 |
| Culture 포스트 | ${cultureCount}개 |
| 총 이미지 | ${totalImages}개 |

## 🚀 다음 단계

1. 각 초안 내용 검토
2. 로컬 미리보기: \`npm run hugo:serve\`
3. 수정 필요시: 직접 파일 편집
4. 발행: \`npm run daily:deploy\`

---
*Generated by OpenClaw Preview Generator*
`;

  return report;
}

async function main() {
  const args = process.argv.slice(2);
  const todayOnly = args.includes('--today');

  console.log(chalk.cyan('\n📋 프리뷰 보고서 생성\n'));

  // 초안 수집
  const drafts = await getDrafts(todayOnly);

  console.log(chalk.dim(`  발견된 초안: ${drafts.length}개`));

  if (drafts.length === 0) {
    console.log(chalk.yellow('\n⚠️ 프리뷰할 초안이 없습니다.'));
    if (todayOnly) {
      console.log(chalk.dim('  --today 옵션 없이 다시 실행해보세요.'));
    }
    process.exit(0);
  }

  // 보고서 생성
  const report = await generatePreviewReport(drafts);

  // 저장
  const reportsDir = join(projectRoot, 'reports');
  await mkdir(reportsDir, { recursive: true });

  const today = new Date().toISOString().split('T')[0];
  const reportPath = join(reportsDir, `preview-${today}.md`);

  await writeFile(reportPath, report, 'utf-8');

  console.log(chalk.green(`\n✅ 보고서 생성 완료: ${reportPath}`));

  // 콘솔에도 간단 요약 출력
  console.log(chalk.white.bold('\n📝 초안 목록:'));
  for (const draft of drafts) {
    const emoji = draft.type === 'travel' ? '🧳' : '🎨';
    const status = draft.draft ? chalk.yellow('초안') : chalk.green('발행준비');
    console.log(`  ${emoji} ${draft.title}`);
    console.log(chalk.dim(`     ${status} | ${draft.wordCount.toLocaleString()}자 | 이미지 ${draft.inlineImageCount + (draft.coverImage ? 1 : 0)}개`));
  }

  console.log(chalk.cyan('\n💡 자세한 내용은 보고서를 확인하세요.'));
}

main().catch((err) => {
  console.error(chalk.red('오류:'), err);
  process.exit(1);
});
